language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t armandoalorro/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true armandoalorro/react-test npm test

after_success:
    - docker build -t armandoalorro/multi-client ./client
    - docker build -t armandoalorro/multi-nginx ./nginx
    - docker build -t armandoalorro/multi-server ./server
    - docker build -t armandoalorro/multi-worker ./worker
    ## login to Docker Hub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    ## push images to Docker Hub
    - docker push armandoalorro/multi-client
    - docker push armandoalorro/multi-nginx
    - docker push armandoalorro/multi-server
    - docker push armandoalorro/multi-worker

deploy:
    edge: true
    provide: elasticbeanstalk
    region: "us-east-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-328747554677"
    bucket_path: "multi-docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
